version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    networks:
      - mosquitto-net

networks:
  mosquitto-net:
    driver: bridge
